### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by aileenzeng** [aileenzeng/sidewalk-docker#26]
This is after running `docker-compose up` on Windows (final step of the README). Related to #5, maybe #24?

```
website_1  | [warn]     module not found: org.geotools#gt-coverage;14.3
website_1  | [warn] ==== local: tried
website_1  | [warn]   /root/.ivy2/local/org.geotools/gt-coverage/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded-ivy: tried
website_1  | [warn]   file:/root/.sbt/preloaded/org.geotools/gt-coverage/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded: tried
website_1  | [warn]   file:////root/.sbt/preloaded/org/geotools/gt-coverage/14.3/gt-coverage-14.3.pom
website_1  | [warn] ==== public: tried
website_1  | [warn]   http://repo1.maven.org/maven2/org/geotools/gt-coverage/14.3/gt-coverage-14.3.pom
website_1  | [warn] ==== Atlassian Releases: tried
website_1  | [warn]   https://maven.atlassian.com/public/org/geotools/gt-coverage/14.3/gt-coverage-14.3.pom
website_1  | [warn] ==== Typesafe Releases Repository: tried
website_1  | [warn]   https://repo.typesafe.com/typesafe/releases/org/geotools/gt-coverage/14.3/gt-coverage-14.3.pom
website_1  | [warn] ==== sonatype-snapshots: tried
website_1  | [warn]   https://oss.sonatype.org/content/repositories/snapshots/org/geotools/gt-coverage/14.3/gt-coverage-14.3.pom
website_1  | [warn] ==== geosolutions: tried
website_1  | [warn]   http://maven.geo-solutions.it/org/geotools/gt-coverage/14.3/gt-coverage-14.3.pom
website_1  | [warn] ==== osgeo: tried
website_1  | [warn]   http://download.osgeo.org/webdav/geotools/org/geotools/gt-coverage/14.3/gt-coverage-14.3.pom
website_1  | [info] Resolving org.geotools#gt-epsg-hsql;14.3 ...
website_1  | [warn]     module not found: org.geotools#gt-epsg-hsql;14.3
website_1  | [warn] ==== local: tried
website_1  | [warn]   /root/.ivy2/local/org.geotools/gt-epsg-hsql/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded-ivy: tried
website_1  | [warn]   file:/root/.sbt/preloaded/org.geotools/gt-epsg-hsql/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded: tried
website_1  | [warn]   file:////root/.sbt/preloaded/org/geotools/gt-epsg-hsql/14.3/gt-epsg-hsql-14.3.pom
website_1  | [warn] ==== public: tried
website_1  | [warn]   http://repo1.maven.org/maven2/org/geotools/gt-epsg-hsql/14.3/gt-epsg-hsql-14.3.pom
website_1  | [warn] ==== Atlassian Releases: tried
website_1  | [warn]   https://maven.atlassian.com/public/org/geotools/gt-epsg-hsql/14.3/gt-epsg-hsql-14.3.pom
website_1  | [warn] ==== Typesafe Releases Repository: tried
website_1  | [warn]   https://repo.typesafe.com/typesafe/releases/org/geotools/gt-epsg-hsql/14.3/gt-epsg-hsql-14.3.pom
website_1  | [warn] ==== sonatype-snapshots: tried
website_1  | [warn]   https://oss.sonatype.org/content/repositories/snapshots/org/geotools/gt-epsg-hsql/14.3/gt-epsg-hsql-14.3.pom
website_1  | [warn] ==== geosolutions: tried
website_1  | [warn]   http://maven.geo-solutions.it/org/geotools/gt-epsg-hsql/14.3/gt-epsg-hsql-14.3.pom
website_1  | [warn] ==== osgeo: tried
website_1  | [warn]   http://download.osgeo.org/webdav/geotools/org/geotools/gt-epsg-hsql/14.3/gt-epsg-hsql-14.3.pom
website_1  | [info] Resolving org.geotools#gt-geotiff;14.3 ...
website_1  | [warn]     module not found: org.geotools#gt-geotiff;14.3
website_1  | [warn] ==== local: tried
website_1  | [warn]   /root/.ivy2/local/org.geotools/gt-geotiff/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded-ivy: tried
website_1  | [warn]   file:/root/.sbt/preloaded/org.geotools/gt-geotiff/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded: tried
website_1  | [warn]   file:////root/.sbt/preloaded/org/geotools/gt-geotiff/14.3/gt-geotiff-14.3.pom
website_1  | [warn] ==== public: tried
website_1  | [warn]   http://repo1.maven.org/maven2/org/geotools/gt-geotiff/14.3/gt-geotiff-14.3.pom
website_1  | [warn] ==== Atlassian Releases: tried
website_1  | [warn]   https://maven.atlassian.com/public/org/geotools/gt-geotiff/14.3/gt-geotiff-14.3.pom
website_1  | [warn] ==== Typesafe Releases Repository: tried
website_1  | [warn]   https://repo.typesafe.com/typesafe/releases/org/geotools/gt-geotiff/14.3/gt-geotiff-14.3.pom
website_1  | [warn] ==== sonatype-snapshots: tried
website_1  | [warn]   https://oss.sonatype.org/content/repositories/snapshots/org/geotools/gt-geotiff/14.3/gt-geotiff-14.3.pom
website_1  | [warn] ==== geosolutions: tried
website_1  | [warn]   http://maven.geo-solutions.it/org/geotools/gt-geotiff/14.3/gt-geotiff-14.3.pom
website_1  | [warn] ==== osgeo: tried
website_1  | [warn]   http://download.osgeo.org/webdav/geotools/org/geotools/gt-geotiff/14.3/gt-geotiff-14.3.pom
website_1  | [info] Resolving org.geotools#gt-main;14.3 ...
website_1  | [warn]     module not found: org.geotools#gt-main;14.3
website_1  | [warn] ==== local: tried
website_1  | [warn]   /root/.ivy2/local/org.geotools/gt-main/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded-ivy: tried
website_1  | [warn]   file:/root/.sbt/preloaded/org.geotools/gt-main/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded: tried
website_1  | [warn]   file:////root/.sbt/preloaded/org/geotools/gt-main/14.3/gt-main-14.3.pom
website_1  | [warn] ==== public: tried
website_1  | [warn]   http://repo1.maven.org/maven2/org/geotools/gt-main/14.3/gt-main-14.3.pom
website_1  | [warn] ==== Atlassian Releases: tried
website_1  | [warn]   https://maven.atlassian.com/public/org/geotools/gt-main/14.3/gt-main-14.3.pom
website_1  | [warn] ==== Typesafe Releases Repository: tried
website_1  | [warn]   https://repo.typesafe.com/typesafe/releases/org/geotools/gt-main/14.3/gt-main-14.3.pom
website_1  | [warn] ==== sonatype-snapshots: tried
website_1  | [warn]   https://oss.sonatype.org/content/repositories/snapshots/org/geotools/gt-main/14.3/gt-main-14.3.pom
website_1  | [warn] ==== geosolutions: tried
website_1  | [warn]   http://maven.geo-solutions.it/org/geotools/gt-main/14.3/gt-main-14.3.pom
website_1  | [warn] ==== osgeo: tried
website_1  | [warn]   http://download.osgeo.org/webdav/geotools/org/geotools/gt-main/14.3/gt-main-14.3.pom
website_1  | [info] Resolving org.geotools#gt-referencing;14.3 ...
website_1  | [warn]     module not found: org.geotools#gt-referencing;14.3
website_1  | [warn] ==== local: tried
website_1  | [warn]   /root/.ivy2/local/org.geotools/gt-referencing/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded-ivy: tried
website_1  | [warn]   file:/root/.sbt/preloaded/org.geotools/gt-referencing/14.3/ivys/ivy.xml
website_1  | [warn] ==== local-preloaded: tried
website_1  | [warn]   file:////root/.sbt/preloaded/org/geotools/gt-referencing/14.3/gt-referencing-14.3.pom
website_1  | [warn] ==== public: tried
website_1  | [warn]   http://repo1.maven.org/maven2/org/geotools/gt-referencing/14.3/gt-referencing-14.3.pom
website_1  | [warn] ==== Atlassian Releases: tried
website_1  | [warn]   https://maven.atlassian.com/public/org/geotools/gt-referencing/14.3/gt-referencing-14.3.pom
website_1  | [warn] ==== Typesafe Releases Repository: tried
website_1  | [warn]   https://repo.typesafe.com/typesafe/releases/org/geotools/gt-referencing/14.3/gt-referencing-14.3.pom
website_1  | [warn] ==== sonatype-snapshots: tried
website_1  | [warn]   https://oss.sonatype.org/content/repositories/snapshots/org/geotools/gt-referencing/14.3/gt-referencing-14.3.pom
website_1  | [warn] ==== geosolutions: tried
website_1  | [warn]   http://maven.geo-solutions.it/org/geotools/gt-referencing/14.3/gt-referencing-14.3.pom
website_1  | [warn] ==== osgeo: tried
website_1  | [warn]   http://download.osgeo.org/webdav/geotools/org/geotools/gt-referencing/14.3/gt-referencing-14.3.pom
website_1  | [info] Resolving com.typesafe.play#play-test_2.10;2.3.8 ...

[...more downloads]

website_1  | [warn]     [FAILED     ] javax.media#jai_core;1.1.3!jai_core.jar: The HTTP response code for http://download.osgeo.org/webdav/geotools/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar did not indicate a success. See log for more detail. (6314ms)
website_1  | [warn]     [FAILED     ] javax.media#jai_core;1.1.3!jai_core.jar: The HTTP response code for http://download.osgeo.org/webdav/geotools/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar did not indicate a success. See log for more detail. (6314ms)
website_1  | [warn] ==== local: tried
website_1  | [warn]   /root/.ivy2/local/javax.media/jai_core/1.1.3/jars/jai_core.jar
website_1  | [warn]   http://download.osgeo.org/webdav/geotools/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
website_1  | [info] downloading http://download.osgeo.org/webdav/geotools/javax/media/jai_codec/1.1.3/jai_codec-1.1.3.jar ...
website_1  | [warn]     [FAILED     ] javax.media#jai_codec;1.1.3!jai_codec.jar: The HTTP response code for http://download.osgeo.org/webdav/geotools/javax/media/jai_codec/1.1.3/jai_codec-1.1.3.jar did not indicate a success. See log for more detail. (38ms)
website_1  | [warn]     [FAILED     ] javax.media#jai_codec;1.1.3!jai_codec.jar: The HTTP response code for http://download.osgeo.org/webdav/geotools/javax/media/jai_codec/1.1.3/jai_codec-1.1.3.jar did not indicate a success. See log for more detail. (38ms)
website_1  | [warn] ==== local: tried
website_1  | [warn]   /root/.ivy2/local/javax.media/jai_codec/1.1.3/jars/jai_codec.jar
website_1  | [warn]   http://download.osgeo.org/webdav/geotools/javax/media/jai_codec/1.1.3/jai_codec-1.1.3.jar
website_1  | [info] downloading http://download.osgeo.org/webdav/geotools/javax/media/jai_imageio/1.1/jai_imageio-1.1.jar ...
website_1  | [warn]     [FAILED     ] javax.media#jai_imageio;1.1!jai_imageio.jar: The HTTP response code for http://download.osgeo.org/webdav/geotools/javax/media/jai_imageio/1.1/jai_imageio-1.1.jar did not indicate a success. See log for more detail. (31ms)
website_1  | [warn]     [FAILED     ] javax.media#jai_imageio;1.1!jai_imageio.jar: The HTTP response code for http://download.osgeo.org/webdav/geotools/javax/media/jai_imageio/1.1/jai_imageio-1.1.jar did not indicate a success. See log for more detail. (31ms)
website_1  | [warn] ==== local: tried
website_1  | [warn]   /root/.ivy2/local/javax.media/jai_imageio/1.1/jars/jai_imageio.jar
website_1  | [warn]   http://download.osgeo.org/webdav/geotools/javax/media/jai_imageio/1.1/jai_imageio-1.1.jar
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | [warn]     ::          UNRESOLVED DEPENDENCIES         ::
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | [warn]     :: org.geotools#gt-coverage;14.3: not found
website_1  | [warn]     :: org.geotools#gt-epsg-hsql;14.3: not found
website_1  | [warn]     :: org.geotools#gt-geotiff;14.3: not found
website_1  | [warn]     :: org.geotools#gt-main;14.3: not found
website_1  | [warn]     :: org.geotools#gt-referencing;14.3: not found
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | [warn]     ::              FAILED DOWNLOADS            ::
website_1  | [warn]     :: ^ see resolution messages for details  ^ ::
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | [warn]     :: javax.media#jai_core;1.1.3!jai_core.jar
website_1  | [warn]     :: javax.media#jai_codec;1.1.3!jai_codec.jar
website_1  | [warn]     :: javax.media#jai_imageio;1.1!jai_imageio.jar
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | sbt.ResolveException: unresolved dependency: org.geotools#gt-coverage;14.3: not found
website_1  | unresolved dependency: org.geotools#gt-epsg-hsql;14.3: not found
website_1  | unresolved dependency: org.geotools#gt-geotiff;14.3: not found
website_1  | unresolved dependency: org.geotools#gt-main;14.3: not found
website_1  | unresolved dependency: org.geotools#gt-referencing;14.3: not found
website_1  | download failed: javax.media#jai_core;1.1.3!jai_core.jar
website_1  | download failed: javax.media#jai_codec;1.1.3!jai_codec.jar
website_1  | download failed: javax.media#jai_imageio;1.1!jai_imageio.jar
website_1  |    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
website_1  |    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
website_1  |    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
website_1  |    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
website_1  |    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
website_1  |    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
website_1  |    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
website_1  |    at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
website_1  |    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
website_1  |    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
website_1  |    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
website_1  |    at xsbt.boot.Using$.withResource(Using.scala:10)
website_1  |    at xsbt.boot.Using$.apply(Using.scala:9)
website_1  |    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
website_1  |    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
website_1  |    at xsbt.boot.Locks$.apply0(Locks.scala:31)
website_1  |    at xsbt.boot.Locks$.apply(Locks.scala:28)
website_1  |    at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
website_1  |    at sbt.IvySbt.withIvy(Ivy.scala:98)
website_1  |    at sbt.IvySbt.withIvy(Ivy.scala:94)
website_1  |    at sbt.IvySbt$Module.withModule(Ivy.scala:115)
website_1  |    at sbt.IvyActions$.update(IvyActions.scala:125)
website_1  |    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
website_1  |    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
website_1  |    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
website_1  |    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
website_1  |    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
website_1  |    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
website_1  |    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
website_1  |    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
website_1  |    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
website_1  |    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
website_1  |    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
website_1  |    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
website_1  |    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
website_1  |    at sbt.std.Transform$$anon$4.work(System.scala:64)
website_1  |    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
website_1  |    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
website_1  |    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
website_1  |    at sbt.Execute.work(Execute.scala:244)
website_1  |    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
website_1  |    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
website_1  |    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
website_1  |    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
website_1  |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
website_1  |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
website_1  |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
website_1  |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
website_1  |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
website_1  |    at java.lang.Thread.run(Thread.java:745)
website_1  | [error] (*:update) sbt.ResolveException: unresolved dependency: org.geotools#gt-coverage;14.3: not found
website_1  | [error] unresolved dependency: org.geotools#gt-epsg-hsql;14.3: not found
website_1  | [error] unresolved dependency: org.geotools#gt-geotiff;14.3: not found
website_1  | [error] unresolved dependency: org.geotools#gt-main;14.3: not found
website_1  | [error] unresolved dependency: org.geotools#gt-referencing;14.3: not found
website_1  | [error] download failed: javax.media#jai_core;1.1.3!jai_core.jar
website_1  | [error] download failed: javax.media#jai_codec;1.1.3!jai_codec.jar
website_1  | [error] download failed: javax.media#jai_imageio;1.1!jai_imageio.jar
website_1  | [error] Total time: 14 s, completed Jul 5, 2018 10:16:58 PM
```

**Comment by jonfroehlich** [comment]
Oh no! I wonder what happened. It looks like https://www.osgeo.org/ is still supported... maybe you just have to find a different end point?

**Comment by aileenzeng** [comment]
Yeah it must have been taken down/moved in the past day or two :/ I found a couple other places where I should hopefully be able to download these from (I’ll try it out later tonight)

**Comment by jonfroehlich** [comment]
Sounds good. Thanks!

**Comment by jonfroehlich** [comment]
Ok. No problem. Thanks for trying.

**Comment by aileenzeng** [comment]
Associated SidewalkWebpage commit on branch `593-move-to-docker`: https://github.com/ProjectSidewalk/SidewalkWebpage/commit/f57d42ec398cdf86fd79f4c207bade85b6b337fd

**Comment by ShivenBhatt** [comment]
From Shiven's:
```
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | [warn]     ::              FAILED DOWNLOADS            ::
website_1  | [warn]     :: ^ see resolution messages for details  ^ ::
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | [warn]     :: javax.media#jai_core;1.1.3!jai_core.jar
website_1  | [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
website_1  | sbt.ResolveException: download failed: javax.media#jai_core;1.1.3!jai_core.jar
website_1  |    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
website_1  |    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
website_1  |    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
website_1  |    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
website_1  |    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
website_1  |    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
website_1  |    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
website_1  |    at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
website_1  |    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
website_1  |    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
website_1  |    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
website_1  |    at xsbt.boot.Using$.withResource(Using.scala:10)
website_1  |    at xsbt.boot.Using$.apply(Using.scala:9)
website_1  |    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
website_1  |    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
website_1  |    at xsbt.boot.Locks$.apply0(Locks.scala:31)
website_1  |    at xsbt.boot.Locks$.apply(Locks.scala:28)
website_1  |    at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
website_1  |    at sbt.IvySbt.withIvy(Ivy.scala:98)
website_1  |    at sbt.IvySbt.withIvy(Ivy.scala:94)
website_1  |    at sbt.IvySbt$Module.withModule(Ivy.scala:115)
website_1  |    at sbt.IvyActions$.update(IvyActions.scala:125)
website_1  |    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
website_1  |    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
website_1  |    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
website_1  |    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
website_1  |    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
website_1  |    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
website_1  |    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
website_1  |    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
website_1  |    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
website_1  |    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
website_1  |    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
website_1  |    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
website_1  |    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
website_1  |    at sbt.std.Transform$$anon$4.work(System.scala:64)
website_1  |    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
website_1  |    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
website_1  |    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
website_1  |    at sbt.Execute.work(Execute.scala:244)
website_1  |    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
website_1  |    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
website_1  |    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
website_1  |    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
website_1  |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
website_1  |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
website_1  |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
website_1  |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
website_1  |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
website_1  |    at java.lang.Thread.run(Thread.java:745)
website_1  | [error] (*:update) sbt.ResolveException: download failed: javax.media#jai_core;1.1.3!jai_core.jar
website_1  | [error] Total time: 664 s, completed Jul 6, 2018 5:19:10 PM
```

**Comment by aileenzeng** [comment]
^ was from not checking out the correct branch.

There were other issues that came up due to a missing `jgridshift` dependency. The fix for that is here: https://github.com/ProjectSidewalk/SidewalkWebpage/commit/c2bdb89224ed6004531002a25bab5fc2669a5a98
