### ISSUE TITLE
Connect website and db services

### ISSUE THREAD

**Issue by aileenzeng** [aileenzeng/sidewalk-docker#8]
The local server is able to start now - it doesn't actually run properly because postgres hasn't been connected yet.

Initial attempt:
```
D-10-18-223-114:website aileen$ docker run -it -p 9000:9000 --name sidewalk-docker_website sidewalk-docker_website
I am the entrypoint!!
Running sbt run...
[info] Loading project definition from /root/app/project
[info] Set current project to sidewalk-webpage (in build file:/root/app/)

--- (Running the application, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0.0.0.0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: java.net.ConnectException: Connection refused.Message:Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
[error] application - 

! @78d8071lc - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.10-2.3.8.jar:2.3.8]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.10-2.3.8.jar:2.3.8]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.10-2.3.8.jar:2.3.8]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.10-2.3.8.jar:2.3.8]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.5.jar:na]
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:144) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21) ~[postgresql-9.3-1102-jdbc4.jar:na]
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_92]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_92]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_92]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_92]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_92]
D-10-18-223-114:website aileen$ docker run -it -p 9000:9000 --name sidewalk-docker_website --link sidewalk-docker_db sidewalk-docker_website
docker: Error response from daemon: Conflict. The container name "/sidewalk-docker_website" is already in use by container "bbb76ba86e2392ce3c256b65b83ae24ff788730beaa8fe9970c3eef18928ae56". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
D-10-18-223-114:website aileen$ docker rm bbb76ba86e2392ce3c256b65b83ae24ff788730beaa8fe9970c3eef18928ae56
bbb76ba86e2392ce3c256b65b83ae24ff788730beaa8fe9970c3eef18928ae56
```

I tried to link the containers (hoped this would be a quick fix) -- this didn't work either:
```
D-10-18-223-114:website aileen$ docker run -it -p 9000:9000 --name sidewalk-docker_website --link 83f4e08fe499 sidewalk-docker_website
docker: Error response from daemon: Cannot link to /sidewalk-docker_db_1, as it does not belong to the default network.
```

**Comment by aileenzeng** [comment]
![image](https://user-images.githubusercontent.com/25534091/42060472-cd90b34e-7adb-11e8-99eb-58162c28e290.png)

This is what's displayed at `localhost:9000`.

**Comment by aileenzeng** [comment]
Seems like the containers are connected:
```
D-10-18-223-114:sidewalk-docker aileen$ docker exec -it sidewalk-docker_website_1 sh
~/app # ping sidewalk
PING sidewalk (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.112 ms
64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.142 ms
64 bytes from 172.19.0.2: seq=2 ttl=64 time=0.142 ms
64 bytes from 172.19.0.2: seq=3 ttl=64 time=0.142 ms
64 bytes from 172.19.0.2: seq=4 ttl=64 time=0.143 ms
64 bytes from 172.19.0.2: seq=5 ttl=64 time=0.218 ms
^C
--- sidewalk ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max = 0.112/0.149/0.218 ms
```

I was able to ping sidewalk from the website container, which is good! Probably this means that I'm having issues w/ naming or something? 

Might need to look into some of the `.conf` files...

**Comment by aileenzeng** [comment]
Hunch: Might need to modify the JDBC name in Sidewalk? ¯\\_(ツ)_/¯

**Comment by aileenzeng** [comment]
Resolved in https://github.com/aileenzeng/sidewalk-docker/commit/16f5c499e8cbe8bad427d67f527aa8c08ac0cbfb :)!!

Requires the following modifications to `applications.conf`:
```
# This is for docker.
# Pulls the from the DOCKER_DB environment variable from the compose file.
db.default.url="jdbc:postgresql://"${?DOCKER_DB}"/sidewalk"
```

(this information is in the `README`)
